# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

google_map_api_key: AIzaSyCLwvADPK2vhk5ypz889HsenDU3yhSm19M
twilio_account_sid: AC7a2a3714a7013c21fc4d2d0266b4ac55
twilio_auth_token: 00b7255b00e87540779243b78471c86e
twilio_phone_number: "+12058395266"
personal: "+14185755632"
# slack_api_token: xoxb-461156293569-4329447238295-DDxX96DasByY078fRrwcqcoY
AWSAccessKeyId: AKIAQ7JF4W2FZGIY2GVZ
AWSSecretKey: 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
freshdesk: HKdDXxuzqj74qW1WGoFO
